### ISSUE TITLE
local Smoke test : TOTAL SUCCESS PERCENTAGE IS: 0.963679 

### ISSUE THREAD

**Issue by kosenhitatchi** [vvv18-vision/assignment_closest-blob-kosenhitatchi#1]
local Smoke test : TOTAL SUCCESS PERCENTAGE IS: 0.963679 @pattacini @vtikha

**Comment by vtikha** [comment]
@kosenhitatchi well done 🎉 , we ran your code on the gradebook machine and you got a similar score (slightly higher 😉 )
